// This file is automatically generated by KBuilder 0.2.0
// PropOsz class definition file

#ifndef KBUILDER_PropOsz_H
#define KBUILDER_PropOsz_H

class KLineEdit;

class QPushButton;
class QLabel;
class QCheckBox;

class Circuit;
class XDevice;

class PropOsz : public QDialog
{
    Q_OBJECT

public:
    PropOsz(QWidget *, const QString &, Circuit *, XDevice *);

private slots:
    void mono();

private:
    void done(int);

    QPushButton *bCancel;
    QPushButton *bOK;
    QLabel *label0;
    KLineEdit *devname;
    QLabel *label1;
    KLineEdit *onCnt;
    QLabel *label2;
    KLineEdit *offCnt;
    QCheckBox *cb_type;

    Circuit *dnet;
    XDevice *dev;
};

#endif
